-- Categorias
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1000, 'Comic books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1001, 'Movies');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1002, 'Books');

-- Fornecedores
INSERT INTO SUPPLIER (ID, NAME) VALUES (1000, 'Panini comics');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1001, 'Amazon');

-- Produtos
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) VALUES (1000, 'Crise nas infinitas terras', 1000, 1000, 10);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) VALUES (1001, 'Interestelar', 1001, 1001, 5);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) VALUES (1002, 'Harry Potter', 1001, 1002, 3);